### ISSUE TITLE
After applying Prime Videos Goes L3

### ISSUE THREAD

**Issue by iamLiquidX** [cyberelon007/widevine-L1#1]
Netflix Starts working in full hd but prime videos doesn't go full hd ever. 😁😁😁

**Comment by cyberelon007** [comment]
Thats the downside of it I can't do anything to get it working, maybe I should add fingerprint spoofing too

**Comment by cyberelon007** [comment]
Thats the downside of it I can't do anything to get it working, maybe I should add fingerprint spoofing too

**Comment by cyberelon** [comment]
Thats the downside of it I can't do anything to get it working, maybe I should add fingerprint spoofing too
