### ISSUE TITLE
Changing device but no L1

### ISSUE THREAD

**Issue by Amanse** [cyberelon007/widevine-L1#3]
I have a Realme 6 Pro and it does have a FHD display and originally supports widevine l1, but i am on PE+ and module is only changing the device but having no effect on L3, will it only work on stock ROM? 
![Screenshot_20201121-022213793](https://user-images.githubusercontent.com/13214574/99850081-bb2e4480-2ba2-11eb-9a6d-d2bc107285da.jpg)

**Comment by cyberelon** [comment]
It doesn't work on third-party device.  This module is specifically made for Xiaomeme devices that have l1 by default, but doesn't supporting l1 on Netflix.

**Comment by Amanse** [comment]
Thanks for replying and the info sir!
can it be possible to build this for other devices? it would be really helpful if you could tell how 😄

**Comment by cyberelon** [comment]
Ya anyone can build it for other devices or brands. Modifying or adding values or system.prop file is enough

**Comment by Amanse** [comment]
Thanks so much!! I will try system.prop file today only. I wanted to ask what makes this module Xiaomeme only? and what device should i select for system.prop? sorry if i am being a bit too much
